# Generated by Django 3.2.10 on 2022-04-12 15:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0002_auto_20220412_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='images/'),
        ),
    ]
